config/routes.rb
Rails.application.routes.draw do
  resources :businesses

  resources :content_items

  get 'contact', to: 'contact#index'

  resources :enquiries

  resources :profiles

  devise_for :users, :controllers => { :registrations => "registrations" }

  root 'home#index'

end

app/controllers/businesses_controller.rb
class BusinessesController < ApplicationController
  before_action :set_business, only: [:show, :edit, :update, :destroy]

  # GET /businesses
  # GET /businesses.json
  def index
    @businesses = Business.all
  end

  # GET /businesses/1
  # GET /businesses/1.json
  def show
  end

  # GET /businesses/new
  def new
    @business = Business.new
  end

  # GET /businesses/1/edit
  def edit
  end

  # POST /businesses
  # POST /businesses.json
  def create
    @business = Business.new(business_params)
    @business.user = current_user

    respond_to do |format|
      if @business.save
        format.html { redirect_to @business, notice: 'Business was successfully created.' }
        format.json { render :show, status: :created, location: @business }
      else
        format.html { render :new }
        format.json { render json: @business.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /businesses/1
  # PATCH/PUT /businesses/1.json
  def update
    respond_to do |format|
      if @business.update(business_params)
        format.html { redirect_to @business, notice: 'Business was successfully updated.' }
        format.json { render :show, status: :ok, location: @business }
      else
        format.html { render :edit }
        format.json { render json: @business.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /businesses/1
  # DELETE /businesses/1.json
  def destroy
    @business.destroy
    respond_to do |format|
      format.html { redirect_to businesses_url, notice: 'Business was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_business
      @business = Business.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def business_params
      params.require(:business).permit(:name, :info, :logo, :website, :email, :phone, :user_id)
    end
end

app/helpers/businesses_helper.rb
module BusinessesHelper
end

app/views/businesses/_form.html.erb
<%= simple_form_for(@business) do |f| %>
  <%= f.error_notification %>

  
  	<div class="form-group">
    	<%= f.input :name, input_html: { class: 'form-control'} %>
  	</div>
  	<div class="form-group">
    	<%= f.input :info, input_html: { class: 'form-control'} %>
  	</div>
  	<div class="form-group">
    	<%= f.input :logo, input_html: { class: 'form-control'} %>
  	</div>
  	<div class="form-group">
    	<%= f.input :website, input_html: { class: 'form-control'} %>
  	</div>
  	<div class="form-group">
    	<%= f.input :email, input_html: { class: 'form-control'} %>
  	</div>
  	<div class="form-group">
    	<%= f.input :phone, input_html: { class: 'form-control'} %>
  	</div>
  

  <div class="form-actions">
    <%= f.button :submit %>
  </div>
<% end %>

app/views/businesses/edit.html.erb
<h1>Editing business</h1>

<%= render 'form' %>

<%= link_to 'Show', @business %> |
<%= link_to 'Back', businesses_path %>

app/views/businesses/index.html.erb
<h1>Listing businesses</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Info</th>
      <th>Logo</th>
      <th>Website</th>
      <th>Email</th>
      <th>Phone</th>
      <th>User</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @businesses.each do |business| %>
      <tr>
        <td><%= business.name %></td>
        <td><%= business.info %></td>
        <td><%= business.logo %></td>
        <td><%= business.website %></td>
        <td><%= business.email %></td>
        <td><%= business.phone %></td>
        <td><%= business.user %></td>
        <td><%= link_to 'Show', business %></td>
        <td><%= link_to 'Edit', edit_business_path(business) %></td>
        <td><%= link_to 'Destroy', business, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Business', new_business_path %>

app/views/businesses/new.html.erb
<h1>New business</h1>

<%= render 'form' %>

<%= link_to 'Back', businesses_path %>

app/views/businesses/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @business.name %>
</p>

<p>
  <strong>Info:</strong>
  <%= @business.info %>
</p>

<p>
  <strong>Logo:</strong>
  <%= @business.logo %>
</p>

<p>
  <strong>Website:</strong>
  <%= @business.website %>
</p>

<p>
  <strong>Email:</strong>
  <%= @business.email %>
</p>

<p>
  <strong>Phone:</strong>
  <%= @business.phone %>
</p>

<p>
  <strong>User:</strong>
  <%= @business.user %>
</p>

<%= link_to 'Edit', edit_business_path(@business) %> |
<%= link_to 'Back', businesses_path %>