config/routes.rb
Rails.application.routes.draw do
  resources :businesses

  resources :content_items

  get 'contact', to: 'contact#index'

  resources :enquiries

  resources :profiles

  devise_for :users, :controllers => { :registrations => "registrations" }

  root 'home#index'

end

app/models/content_item.rb
class ContentItem < ActiveRecord::Base
end

app/controllers/content_items_controller.rb
class ContentItemsController < ApplicationController
  before_action :set_content_item, only: [:show, :edit, :update, :destroy]
  skip_before_action :authenticate_user!
  
  # GET /content_items
  # GET /content_items.json
  def index
    @content_items = ContentItem.all
  end

  # GET /content_items/1
  # GET /content_items/1.json
  def show
  end

  # GET /content_items/new
  def new
    @content_item = ContentItem.new
  end

  # GET /content_items/1/edit
  def edit
  end

  # POST /content_items
  # POST /content_items.json
  def create
    @content_item = ContentItem.new(content_item_params)

    respond_to do |format|
      if @content_item.save
        format.html { redirect_to @content_item, notice: 'Content item was successfully created.' }
        format.json { render :show, status: :created, location: @content_item }
      else
        format.html { render :new }
        format.json { render json: @content_item.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /content_items/1
  # PATCH/PUT /content_items/1.json
  def update
    respond_to do |format|
      if @content_item.update(content_item_params)
        format.html { redirect_to @content_item, notice: 'Content item was successfully updated.' }
        format.json { render :show, status: :ok, location: @content_item }
      else
        format.html { render :edit }
        format.json { render json: @content_item.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /content_items/1
  # DELETE /content_items/1.json
  def destroy
    @content_item.destroy
    respond_to do |format|
      format.html { redirect_to content_items_url, notice: 'Content item was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_content_item
      @content_item = ContentItem.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def content_item_params
      params.require(:content_item).permit(:title, :body)
    end
end

app/helpers/content_items_helper.rb
module ContentItemsHelper
end

app/views/content_items/_form.html.erb
<%= simple_form_for(@content_item) do |f| %>
  <%= f.error_notification %>

  
  	<div class="form-group">
    	<%= f.input :title, input_html: { class: 'form-control'} %>
  	</div>
  	<div class="form-group">
    	<%= f.input :body, input_html: { class: 'form-control ckeditor'} %>
  	</div>
  

  <div class="form-actions">
    <%= f.button :submit %>
  </div>
<% end %>

<script>
  $('.ckeditor').ckeditor({
    //optional config...
  });
</script>

app/views/content_items/edit.html.erb
<h1>Editing content_item</h1>

<%= render 'form' %>

<%= link_to 'Show', @content_item %> |
<%= link_to 'Back', content_items_path %>

app/views/content_items/index.html.erb
<h1>Listing content_items</h1>

<table>
  <thead>
    <tr>
      <th>Title</th>
      <th>Body</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @content_items.each do |content_item| %>
      <tr>
        <td><%= content_item.title %></td>
        <td><%= content_item.body %></td>
        <td><%= link_to 'Show', content_item %></td>
        <td><%= link_to 'Edit', edit_content_item_path(content_item) %></td>
        <td><%= link_to 'Destroy', content_item, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Content item', new_content_item_path %>

app/views/content_items/new.html.erb
<h1>New content_item</h1>

<%= render 'form' %>

<%= link_to 'Back', content_items_path %>

app/views/content_items/show.html.erb
<p id="notice"><%= notice %></p>


<h2><%= @content_item.title %></h2>


  <%= @content_item.body.html_safe %>


<%= link_to 'Edit', edit_content_item_path(@content_item) %> |
<%= link_to 'Back', content_items_path %>