config/routes.rb
Rails.application.routes.draw do
  resources :businesses

  resources :content_items

  get 'contact', to: 'contact#index'

  resources :enquiries

  resources :profiles

  devise_for :users, :controllers => { :registrations => "registrations" }

  root 'home#index'

end

app/models/enquiry.rb
class Enquiry < ActiveRecord::Base
	validates :name, :email, :message, presence: true
end

app/controllers/enquiries_controller.rb
class EnquiriesController < ApplicationController
  before_action :set_enquiry, only: [:show, :edit, :update, :destroy]
  skip_before_action :authenticate_user!, only: :create
  # GET /enquiries
  # GET /enquiries.json
  def index
    @enquiries = Enquiry.all
  end

  # GET /enquiries/1
  # GET /enquiries/1.json
  def show
  end

  # GET /enquiries/new
  def new
    @enquiry = Enquiry.new
  end

  # GET /enquiries/1/edit
  def edit
  end

  # POST /enquiries
  # POST /enquiries.json
  def create
    @enquiry = Enquiry.new(enquiry_params)

    respond_to do |format|
      if @enquiry.save
        format.html { redirect_to root_path, notice: 'Thank you for your enquiry.' }
        EnquiryMailerJob.new.async.perform(@enquiry.id)
        format.json { render :show, status: :created, location: @enquiry }
      else
        format.html { render :new }
        format.json { render json: @enquiry.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /enquiries/1
  # PATCH/PUT /enquiries/1.json
  def update
    respond_to do |format|
      if @enquiry.update(enquiry_params)
        format.html { redirect_to @enquiry, notice: 'Enquiry was successfully updated.' }
        format.json { render :show, status: :ok, location: @enquiry }
      else
        format.html { render :edit }
        format.json { render json: @enquiry.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /enquiries/1
  # DELETE /enquiries/1.json
  def destroy
    @enquiry.destroy
    respond_to do |format|
      format.html { redirect_to enquiries_url, notice: 'Enquiry was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_enquiry
      @enquiry = Enquiry.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def enquiry_params
      params.require(:enquiry).permit(:name, :email, :message, :phone)
    end
end

app/helpers/enquiries_helper.rb
module EnquiriesHelper
end

app/views/enquiries/_form.html.erb
<%= simple_form_for(@enquiry) do |f| %>
  <%= f.error_notification %>

  
  	<div class="form-group">
    	<%= f.input :name, input_html: { class: 'form-control'} %>
  	</div>
  	<div class="form-group">
    	<%= f.input :email, input_html: { class: 'form-control'} %>
  	</div>
  	<div class="form-group">
    	<%= f.input :message, input_html: { class: 'form-control'} %>
  	</div>
  	<div class="form-group">
    	<%= f.input :phone, input_html: { class: 'form-control'} %>
  	</div>
  

  <div class="form-actions">
    <%= f.button :submit %>
  </div>
<% end %>

app/views/enquiries/edit.html.erb
<h1>Editing enquiry</h1>

<%= render 'form' %>

<%= link_to 'Show', @enquiry %> |
<%= link_to 'Back', enquiries_path %>

app/views/enquiries/index.html.erb
<h1>Listing enquiries</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Email</th>
      <th>Message</th>
      <th>Phone</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @enquiries.each do |enquiry| %>
      <tr>
        <td><%= enquiry.name %></td>
        <td><%= enquiry.email %></td>
        <td><%= enquiry.message %></td>
        <td><%= enquiry.phone %></td>
        <td><%= link_to 'Show', enquiry %></td>
        <td><%= link_to 'Edit', edit_enquiry_path(enquiry) %></td>
        <td><%= link_to 'Destroy', enquiry, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Enquiry', new_enquiry_path %>

app/views/enquiries/new.html.erb
<h1>New enquiry</h1>

<%= render 'form' %>

<%= link_to 'Back', enquiries_path %>

app/views/enquiries/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @enquiry.name %>
</p>

<p>
  <strong>Email:</strong>
  <%= @enquiry.email %>
</p>

<p>
  <strong>Message:</strong>
  <%= @enquiry.message %>
</p>

<p>
  <strong>Phone:</strong>
  <%= @enquiry.phone %>
</p>

<%= link_to 'Edit', edit_enquiry_path(@enquiry) %> |
<%= link_to 'Back', enquiries_path %>